-- MySQL Script generated by MySQL Workbench
-- Wed Jul 18 11:26:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cinewild
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinewild
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinewild` DEFAULT CHARACTER SET utf8 ;
USE `cinewild` ;

-- -----------------------------------------------------
-- Table `cinewild`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cinewild`.`movies` ;

CREATE TABLE IF NOT EXISTS `cinewild`.`movies` (
  `idmovies` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NULL,
  `release_date` DATE NULL,
  `director` VARCHAR(250) NULL,
  `with_` VARCHAR(250) NULL,
  `kinds` VARCHAR(250) NULL,
  `press_note` VARCHAR(250) NULL,
  `spectator_note` VARCHAR(250) NULL,
  `description` TEXT NULL,
  `poster` VARCHAR(250) NULL,
  `video` VARCHAR(250) NULL,
  PRIMARY KEY (`idmovies`))
ENGINE = InnoDB;

USE `cinewild` ;

-- -----------------------------------------------------
-- Placeholder table for view `cinewild`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinewild`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `cinewild`.`view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `cinewild`.`view1` ;
DROP TABLE IF EXISTS `cinewild`.`view1`;
USE `cinewild`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
